-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 06-10-2022 a las 20:56:51
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `solidarid-activa`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

CREATE TABLE `users` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `activity_type` varchar(255) DEFAULT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `what_like` varchar(1000) DEFAULT NULL,
  `what_offer` varchar(1000) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`id`, `name`, `activity_type`, `contact`, `location`, `photo`, `what_like`, `what_offer`, `title`) VALUES
(108, 'Ana María', 'baby', 'anam@gmail.com', 'Grado', 'https://www.clarin.com/img/2021/03/16/EHCuEWLKI_720x0__1.jpg', 'Necesitaba apoyo para mi hija de 12 años en las tareas de matematicas, e ingles.', 'Paseo mascotas, y tambien algo de adiestramiento.', 'Clases Particulares'),
(107, 'Bernardino', 'senior', 'dani@dani33.com', 'gijon', 'https://static6.depositphotos.com/1003098/571/i/600/depositphotos_5710810-stock-photo-angry-old-man.jpg', 'juagar a futbol', 'Ver futboleee', 'abuelito del Oviedo'),
(105, 'aide', 'baby', 'aide@aide.com', 'oviedo', 'https://images.ecestaticos.com/sB6jzkMi8Fgo6DCzqMZ3Ad3V_Nk=/0x110:2120x1301/1600x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fdf9%2Fc81%2F2e4%2Fdf9c812e4dfb91f7cd15e122030a4e68.jpg', 'salir, beber el rollo de siempre , meterme mil rayas hablar con la gente', 'salir, beber el rollo de siempre , meterme mil rayas hablar con la gente', 'Fiestaaaaaaaaaaaaaa'),
(103, 'aide', 'baby', 'aide@aide.com', 'Oviedo', 'https://images.ecestaticos.com/sB6jzkMi8Fgo6DCzqMZ3Ad3V_Nk=/0x110:2120x1301/1600x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fdf9%2Fc81%2F2e4%2Fdf9c812e4dfb91f7cd15e122030a4e68.jpg', 'salir, beber el rollo de siempre , meterme mil rayas hablar con la gente', 'salir, beber el rollo de siempre , meterme mil rayas hablar con la gente', 'Fiestaaaaaaaaaaaaaa'),
(17, 'HILDA ', 'senior', 'fran.afull@live.cl	', 'Navia', 'https://adoptaunabuelo.org/wp-content/uploads/2021/01/DSC07941-copia-1024x775.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(9, 'FERNANDO ', 'senior', 'carlosaguileram@hotmail.com	', 'Oviedo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoiq_ET2R7pDxLkV8Q5Q6hj7NRISwKbWmBLw&usqp=CAU', 'Mi abuela toma medicacion y habria que controlar que se tomara lo que le corresponde. Hay un guion en la nevera. Es entrañable.', 'Cocina muy bien y seguro que ofrece un buen cocido, se defiende bastante bien en este ambito. ', 'Vigilar a abuela'),
(19, 'FRANCISCO ', 'senior', 'ikis_rojo@hotmail.com	', 'Gijon', 'https://s3.abcstatics.com/media/familia/2020/04/08/abuelosabrazo-kLAG--620x349@abc.jpg', 'Dar un paseo a media tarde y charlar sobre deportes o sobre lo mal que lo esta haciendo el gobierno son sus aficiones. Quiza podriais pasear juntos?', 'A parte de la buena conversacion, de aportar consejos sobre la vida, tambien sabe solucionar cualquier problema electrico. No esta para trabajar pero si para dar consejos sobre como solucionar algun problema. 50 años de experiencia.', 'Abuela entrañable'),
(20, 'RENE ', 'senior', '654852357', 'Mieres', 'https://madreshoy.com/wp-content/uploads/2022/07/abuelos-2.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(21, 'ADRIAN ', 'senior', 'daniela_aguilera_m500@hotmail.com	', 'Oviedo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs8Qc7jwGZJ9PF4aqSI_UEv-NVwUlVjEHV-g&usqp=CAU', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(8, 'KATTY ', 'senior', 'katagardu@yahoo.com', 'Oviedo', 'https://felizvita.com/wp-content/uploads/2019/12/perdida-de-peso-en-ancianos-cab.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(23, 'GERARDO ', 'senior', '642587963', 'Gijon', 'https://www.larescvalenciana.org/wp-content/uploads/2016/02/hiporexia.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(7, 'RICARDO', 'general', 'alexus3@hotmail.com	', 'Aviles', 'https://www.mundopsicologos.com/site/article/60606/50895/las-10-cualidades-de-una-persona-mas-valoradas-0_ai1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Doy clases de ingles'),
(25, 'CARLOS', 'general', 'capitanaguilera@hotmail.com	', 'Langreo', 'https://images.ecestaticos.com/-f-ySwBW7Mp-ggDplxXveJ0bCNQ=/0x0:991x445/992x446/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F743%2F930%2F270%2F743930270aabd407a594e0f8b8d5dbe9.jpg', 'Tengo opcion de ver infinidad de deportes por tv, pero solo no son entretenidos. Busco a alguien que sea aficionado al sporting que le guste pasar la tarde viendo un partido y disfrutando una conversacion.', 'Doy clases de ingles, graduado en ingles con experiencia en adultos', 'Ver deportes juntos'),
(26, 'ISABEL', 'general', 'luuuuuuci@hotmail.com	', 'Gijon', 'https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2020/03/primera-persona-viva-mil-anos-podria-haber-nacido-ya-experto-antienvejecimiento-1881019.jpg', 'Necesitaria clases de ingles, sobre todo conversacion, estoy preparando oposiciones.', 'Podria hacer recados, como la compra, ir a la farmacia, acompañar a visitas medicas.....', 'Clases de ingles'),
(6, 'GUILLERMO ', 'general', '64852316', 'Oviedo', 'https://www.isesinstituto.com/sites/default/files/istock-1158245282.jpg', 'Busco un amante de los animales que pueda sacar a pasear a mi perro por las mañanas', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(28, 'DANTE ', 'general', 'eduardo.arancibia@grange.cl	', 'Langreo', 'https://images.ecestaticos.com/DGokxoLjR8N_3GIdyO5vuCBd68I=/0x88:1694x1039/1600x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F1fe%2F160%2Fe7d%2F1fe160e7dd58d20124b71fb653c66c1d.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(5, 'ENRIQUE', 'general', 'martacam2002@yahoo.com	', 'Oviedo', 'https://www.larazon.es/resizer/hFdmRwhL_vYY9YhIIq-42Mw0x8c=/600x400/smart/filters:format(jpg)/cloudfront-eu-central-1.images.arcpublishing.com/larazon/3RHZBDGMDBDKDCRIUIPDUCTKQM.jpeg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(30, 'ERNESTO', 'general', 'aargomedo@hecsa.cl	', 'Aviles', 'https://images.ecestaticos.com/RXdIj4WU-bCk6M7ZO1OFSfOwoGI=/0x0:990x557/1600x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F62c%2Fe5d%2F314%2F62ce5d3141c0b670144a692b7f6a21fa.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(31, 'CARMEN GLORIA ', 'general', 'bantomaui@gmail.com	', 'Gijon', 'https://www.cancer.net/sites/cancer.net/files/styles/blog_media/public/jose_enrique_gonzales_nogales.png?itok=a3iqIdL_', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(4, ' VALENTINA ', 'general', 'pablo.calderon.cadiz@gmail.com	', 'Mieres', 'https://www.batiburrillo.net/wp-content/uploads/2019/04/Localiza-personas-utilizando-el-motor-de-bu%CC%81squeda-Pipl.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(33, 'EWRQ', 'pets', 'ERQ', 'EWRQWE', 'RQWERQ', 'RQEWR', 'WQER', 'EWQRQWE'),
(3, '', '', '', '', '', '', '', ''),
(35, 'CHRISTOPHER ', 'pets', 'fgregoriog@vtr.net	', 'Oviedo', 'https://imagenes.20minutos.es/files/image_990_v3/uploads/imagenes/2021/04/10/perro.jpeg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet'),
(36, 'MICHAEL ', 'pets', 'cfalvear@hotmail.com', 'Gijon', 'https://estaticos-cdn.elperiodico.com/clip/3ce472f0-c77c-4fe7-9850-1d30be7abd8f_alta-libre-aspect-ratio_default_0.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=109;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
